### ISSUE TITLE
Package Representation

### ISSUE THREAD

**Issue by dsanmartins** [kieler/klassviz#9]
Hello, 

Is it possible to represent a package in this diagram?. I know that it is a class diagram but maybe the feature exist. I am interesting in drawing a component diagram but this is the closest thing I found.

Regards,

Daniel.

**Comment by le-cds** [comment]
@dsanmartins Yes, that is possible, Daniel. Simply tick the _Package hierarchy_ option in the diagram view. However, the representation of packages could certainly be improved. Still, perhaps it already works for you.
